### ISSUE TITLE
Translation updates

### ISSUE THREAD

**Issue by Siggi0904** [yfdyh000/tabutils#130]
Hi,
can u update the pot file for translations and can u use Transifex or Babelzilla for online translation help?
Transifex would be the best, I think.

There are open and misspelled translations in german e.g.

**Comment by yfdyh000** [comment]
I suggest you update the file(s) and submit a pull request.
Due to the nature of the project and the life cycle approaches to end (Firefox 57), I don't want to introduce new issues and big changes. So, I still hesitate to maintain a translation platform for changes.

You can update it via [the](https://help.github.com/articles/editing-files-in-your-repository/) Github website or git toolchain locally.

**Comment by Siggi0904** [comment]
I don't have a build environment.
It would be nice that you push a updated pot file for translations.
Then I'll send a pull request.

Do you think, you can develop a new plugin for Firefox >=57?
Perhabs we have o use PaleMoon or the last working Firefox then.

**Comment by yfdyh000** [comment]
It's just a zip package. You can edit the files directly in [the directory](https://github.com/yfdyh000/tabutils/tree/Fixed/chrome/locale/de) through the website.
I hope the changes are not too large, and there is no error to break the file syntax.

>Do you think, you can develop a new plugin for Firefox >=57?

Unless Mozilla lengthens the timeline, otherwise it is almost impossible. I watch the TMP author's approach, and he said he might develop one from scratch.

>Perhabs we have o use PaleMoon or the last working Firefox then.

This is a final practice, it will also be a lot of people practice.
But I still hesitate for bringing changes, I may not have enough energy for QA.

**Comment by Siggi0904** [comment]
I've updated the german translation from here: https://github.com/yfdyh000/tabutils/tree/Fixed/chrome/locale/de

Can u merge the two files please?

[german.zip](https://github.com/yfdyh000/tabutils/files/752922/german.zip)
