### ISSUE TITLE
Is this going to be signed at some point?

### ISSUE THREAD

**Issue by Morthawt** [yfdyh000/tabutils#54]
Will this Firefox extension be signed?

**Comment by yfdyh000** [comment]
I have not received any news since #2, although I did not go to ask or urge.
`Queue Position: 9 of 152` at this time. See also #11.

Fortunately, we still have time to wait.
https://blog.mozilla.org/addons/2015/09/16/extending-the-deadline-for-add-on-signing/

Before the signing is completed, see #43.

**Comment by yfdyh000** [comment]
Received `Mozilla Add-ons: Tab Utilities Fixed 1.5.2015.09.12 Preliminary Reviewed`.

https://addons.mozilla.org/firefox/addon/tab-utilities-fixed/versions/
